title: Brizizco
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: boxed
style: classic
palette: green
mode: light
base_font: serif
footer:
  logo: images/classic/logo.svg
  logo_alt: DIY logo
  has_primary_nav: true
  primary_nav_title: Company
  primary_nav_links:
    - label: BRIZIZCO
      url: /about
      style: link
    - label: KOCHI
      url: /style-guide
      style: link
  has_secondary_nav: true
  secondary_nav_title: Blog
  secondary_nav_links:
    - label: News
      url: /blog/category/news
      style: link
    - label: General
      url: /blog/category/general
      style: link
    - label: Tutorials
      url: /blog/category/tutorials
      style: link
  has_tertiary_nav: true
  tertiary_nav_title: Legal
  tertiary_nav_links:
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: link
      has_icon: true
      icon: twitter
      icon_position: center
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: link
      has_icon: true
      icon: github
      icon_position: center
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
    - label: YouTube
      url: 'https://www.youtube.com/'
      style: link
      has_icon: true
      icon: youtube
      icon_position: center
      new_window: true
    - label: Vimeo
      url: 'https://vimeo.com/'
      style: link
      has_icon: true
      icon: vimeo
      icon_position: center
      new_window: true
  content: >-
    &copy; Brizizco. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://fierce-ant-ad781.netlify.app'
